server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://innoforest.cktwvwfzgjx9.ap-northeast-2.rds.amazonaws.com/mark?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: innoforest
    password: yB90JSO4fiixlX6OQ4le
    driver-class-name: com.mysql.cj.jdbc.Driver

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/mark
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: create
